version: 2

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

submodules:
  include: all

build:
  image: latest

