version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3"
  jobs:
    pre_install:
      - pip install mkdocs-material mkdocstrings==0.27.0 mkdocs-jupyter mkdocstrings-python mkdocs-material-extensions

mkdocs:
  configuration: mkdocs.yml


